#############################################################################
# Makefile for building: testui.app/Contents/MacOS/testui
# Generated by qmake (3.0) (Qt 5.1.0) on: Fri Jul 12 15:16:00 2013
# Project:  UIToolkitTest.pro
# Template: app
# Command: /Users/bisegni/Qt/5.1.0/clang_64/bin/qmake -spec macx-xcode -o testui.xcodeproj/project.pbxproj UIToolkitTest.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/bisegni/Qt/5.1.0/clang_64/bin/qmake
testui.xcodeproj/project.pbxproj: UIToolkitTest.pro /Users/bisegni/Qt/5.1.0/clang_64/mkspecs/macx-xcode/qmake.conf /Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/spec_pre.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/qdevice.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/device_config.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/shell-unix.conf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/unix.conf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/mac.conf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/macx.conf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/gcc-base.conf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/g++-base.conf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/g++-macx.conf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/qconfig.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/qt_functions.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/qt_config.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/macx-xcode/qmake.conf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/spec_post.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/default_pre.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/unix/default_pre.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/resolve_config.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/default_post.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/warn_on.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/qt.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/resources.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/moc.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/uic.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/unix/thread.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/mac/rez.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/exceptions.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/yacc.prf \
		/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/lex.prf \
		UIToolkitTest.pro \
		/Users/bisegni/Qt/5.1.0/clang_64/lib/QtSvg.framework/QtSvg.prl \
		/Users/bisegni/Qt/5.1.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/bisegni/Qt/5.1.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/bisegni/Qt/5.1.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-xcode -o testui.xcodeproj/project.pbxproj UIToolkitTest.pro
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/spec_pre.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/qdevice.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/device_config.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/shell-unix.conf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/unix.conf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/mac.conf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/macx.conf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/gcc-base.conf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/g++-base.conf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/common/g++-macx.conf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/qconfig.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_bootstrap.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_clucene.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_v8.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/qt_functions.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/qt_config.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/macx-xcode/qmake.conf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/spec_post.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/default_pre.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/unix/default_pre.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/resolve_config.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/default_post.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/mac/sdk.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/mac/default_post.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/warn_on.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/qt.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/resources.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/moc.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/unix/opengl.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/uic.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/unix/thread.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/mac/rez.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/testcase_targets.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/exceptions.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/yacc.prf:
/Users/bisegni/Qt/5.1.0/clang_64/mkspecs/features/lex.prf:
UIToolkitTest.pro:
/Users/bisegni/Qt/5.1.0/clang_64/lib/QtSvg.framework/QtSvg.prl:
/Users/bisegni/Qt/5.1.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/bisegni/Qt/5.1.0/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/bisegni/Qt/5.1.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-xcode -o testui.xcodeproj/project.pbxproj UIToolkitTest.pro

qmake_all: FORCE

