{
 "title": "CDS Storage Queue",
 "description": "Metriche sulla gestione dello storage dei CDS",
 "tags": [
  "CHAOS",
  "storage"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CDS Storage Queue Element",
   "type": "graph",
   "description": "Is the number of element that are waiting to be store by the storage driver",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mds_storage_queue{type=\"queued_element\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "sum(mds_storage_queue{type=\"queued_element\"})",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "MongoDB Driver Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(mds_mongodb_io_rate{type=\"write_byte_sec\"})"
    }
   ]
  },
  {
   "title": "Rejected Element",
   "type": "graph",
   "description": "Is the number of element that have waited to long(timeout) to be inserted into storage queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mds_storage_queue_rejected[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(mds_storage_queue_rejected[1m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "MongoDB Read Data Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(mds_mongodb_io_rate{type=\"read_byte_sec\"})"
    }
   ]
  },
  {
   "title": "CDS Storage Queue Size",
   "type": "graph",
   "description": "Is the size of all element in queue that are waiting to be store by the storage driver",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "mds_storage_queue{type=\"queued_data\"}",
     "legendFormat": "{{type}}-{{instance}}"
    },
    {
     "expr": "sum(mds_storage_queue{type=\"queued_data\"})",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Rx Direct IO Dispatcher",
   "type": "graph",
   "description": "Is the data rate of the the overall messages received by the direct io dispatcher.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rx_bandwidth_direct_io_dispatcher"
    },
    {
     "expr": "sum(rx_bandwidth_direct_io_dispatcher)",
     "legendFormat": "Sum"
    }
   ]
  }
 ]
}