# -*- mode: python; -*-
# build file for ChaosLibrary
# this requires scons
# you can get from http://www.scons.org
# then just type scons

EnsureSConsVersion(0, 98, 4) # this is a common version known to work

import os
import sys
import imp
import types
import re
import shutil
import urllib
import urllib2
import socket
import time
import socket
import subprocess

buildMode = ARGUMENTS.get('mode', 'release')   #holds current mode
debugcflags = ['-Wall', '-GX', '-EHsc', '-DDEBUG']   #extra compile flags for debug
releasecflags = ['-O2', '-EHsc', '-DNDEBUG']         #extra compile flags for release

print '**** Compiling in ' + buildMode + ' mode...'

# --- options ----

options = {}

def add_option( name, help , nargs , contibutesToVariantDir , dest=None ):

    if dest is None:
        dest = name

    AddOption( "--" + name , 
                dest=dest,
                type="string",
                nargs=nargs,
                action="store",
                help=help )

    options[name] = { "help" : help ,
                      "nargs" : nargs , 
                      "contibutesToVariantDir" : contibutesToVariantDir ,
                      "dest" : dest } 

def get_option( name ):
    return GetOption( name )

def has_option( name ):
    x = get_option( name )
    if x is None:
        return False

    if x == False:
        return False

    if x == "":
        return False

    return True

def get_variant_dir():

    a = []

    for name in options:
        o = options[name]
        if not has_option( o["dest"] ):
            continue
        if not o["contibutesToVariantDir"]:
            continue

        if o["nargs"] == 0:
            a.append( name )
        else:
            a.append( name + "-" + get_option( name ) )

    s = "build/"

    if len(a) > 0:
        a.sort()
        s += "/".join( a ) + "/"

    return s

#---------add option tomake the Chaos Lib Shared
libNameUIToolkit = 'chaos_uitoolkit'

add_option( "static", "build the chaos cu toolkit shared" , 0 , False )
add_option( "prefix", "build the chaos cu toolkit shared" , 1 , False )
if has_option( "prefix" ):
    installDir = GetOption( "prefix" )
else:
    installDir = "/usr/local"

print "prefix:",installDir
print "libName:",libNameUIToolkit



num_cpu = int(os.environ.get('NUM_CPU', 2))
SetOption('num_jobs', num_cpu)
print "running with -j", GetOption('num_jobs')

env = Environment()  # Initialize the environment

#setup the version
subprocess.call(os.path.abspath("../Common/version.sh"), shell=True)

#make sure the sconscripts can get to the variables
Export('env', 'buildMode', 'debugcflags', 'releasecflags')

sourceFiles = Glob( "*.cpp" )
sourceFiles += Glob( "Common/*.cpp" )
sourceFiles += Glob( "HighLevelApi/*.cpp" )
sourceFiles += Glob( "LowLevelApi/*.cpp" )
sourceFiles += Glob( "DataSystem/*.cpp" )
sourceFiles += Glob( "RpcSystem/*.cpp" )

if buildMode == 'debug':
   env.Append(CCFLAGS=debugcflags)
else:
   env.Append(CCFLAGS=releasecflags)

if has_option( "static" ):
    libName = str( env.StaticLibrary(libNameUIToolkit, sourceFiles)[0] )
else:
    env.Append(LIBPATH = ['/usr/lib', '/usr/local/lib'])
    libNameUIToolkit = str( env.SharedLibrary(libNameUIToolkit, sourceFiles, LIBS=['boost_program_options', 'boost_system','boost_thread','boost_chrono','boost_regex','memcached','msgpack','msgpack-rpc','mpio', 'chaos_common'])[0] )
print "Lib file created: " + libNameUIToolkit
    
#headers
for id in [ "", "Common/", "HighLevelApi/", "LowLevelApi/", "DataSystem/", "RpcSystem/"]:
    for hFile in Glob( id + "*.h" ):
        installHeaderPath = installDir + "/" + "include" + "/chaos/ui_toolkit/" + id
        env.Install( installHeaderPath , hFile )
    env.Alias('install-inc', [installHeaderPath])

#lib
print "install library into: "+installDir + "/lib/"
env.Install( installDir + "/lib/", libNameUIToolkit )
env.Alias('install-lib', [installDir + "/lib/"])

env.Alias('install', ['install-lib', 'install-inc'])
