package it.infn.chaos.mds;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class DeviceClassListVaadin extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private Button buttonCloseView;
	@AutoGenerated
	private Button buttonSave;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_6;
	@AutoGenerated
	private Button buttonDel;
	@AutoGenerated
	private Button buttonNew;
	@AutoGenerated
	private Table tableAssociation;
	public Button getButtonCloseView() {
		return buttonCloseView;
	}

	

	/**
	 * The constructor should first build the main layout, set the composition root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual editor.
	 */
	public DeviceClassListVaadin() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public Button getButtonDel() {
		return buttonDel;
	}

	public Button getButtonNew() {
		return buttonNew;
	}

	public Table getTableAssociation() {
		return tableAssociation;
	}


	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		mainLayout.addComponent(horizontalLayout_3);
		
		return mainLayout;
	}



	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("100.0%");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		horizontalLayout_3.addComponent(verticalLayout_2);
		
		return horizontalLayout_3;
	}



	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(false);
		
		// tableAssociation
		tableAssociation = new Table();
		tableAssociation.setCaption("Device Classes");
		tableAssociation.setImmediate(false);
		tableAssociation.setWidth("100.0%");
		tableAssociation.setHeight("-1px");
		verticalLayout_2.addComponent(tableAssociation);
		
		// horizontalLayout_6
		horizontalLayout_6 = buildHorizontalLayout_6();
		verticalLayout_2.addComponent(horizontalLayout_6);
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		verticalLayout_2.addComponent(horizontalLayout_4);
		verticalLayout_2.setComponentAlignment(horizontalLayout_4,
				new Alignment(48));
		
		return verticalLayout_2;
	}



	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_6() {
		// common part: create layout
		horizontalLayout_6 = new HorizontalLayout();
		horizontalLayout_6.setImmediate(false);
		horizontalLayout_6.setWidth("-1px");
		horizontalLayout_6.setHeight("-1px");
		horizontalLayout_6.setMargin(true);
		horizontalLayout_6.setSpacing(true);
		
		// buttonNew
		buttonNew = new Button();
		buttonNew.setCaption("New");
		buttonNew.setImmediate(true);
		buttonNew.setWidth("-1px");
		buttonNew.setHeight("-1px");
		horizontalLayout_6.addComponent(buttonNew);
		horizontalLayout_6.setComponentAlignment(buttonNew, new Alignment(33));
		
		// buttonDel
		buttonDel = new Button();
		buttonDel.setCaption("Del");
		buttonDel.setImmediate(true);
		buttonDel.setWidth("-1px");
		buttonDel.setHeight("-1px");
		horizontalLayout_6.addComponent(buttonDel);
		
		return horizontalLayout_6;
	}



	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("-1px");
		horizontalLayout_4.setHeight("-1px");
		horizontalLayout_4.setMargin(false);
		
		// buttonSave
		buttonSave = new Button();
		buttonSave.setCaption("Save");
		buttonSave.setImmediate(false);
		buttonSave.setDescription("Save Modifications");
		buttonSave.setWidth("-1px");
		buttonSave.setHeight("-1px");
		horizontalLayout_4.addComponent(buttonSave);
		
		// buttonCloseView
		buttonCloseView = new Button();
		buttonCloseView.setCaption("Close");
		buttonCloseView.setImmediate(true);
		buttonCloseView.setWidth("-1px");
		buttonCloseView.setHeight("-1px");
		horizontalLayout_4.addComponent(buttonCloseView);
		horizontalLayout_4.setComponentAlignment(buttonCloseView,
				new Alignment(48));
		
		return horizontalLayout_4;
	}



	public Button getButtonSave() {
		// TODO Auto-generated method stub
		return buttonSave;
	}
}
