import os
num_cpu = int(os.environ.get('NUM_CPU', 2))
SetOption('num_jobs', num_cpu)
print "running with -j", GetOption('num_jobs')

buildMode = ARGUMENTS.get('mode', 'release')   #holds current mode
debugcflags = ['-Wall', '-DDEBUG']   #extra compile flags for debug
releasecflags = ['-O2', '-DNDEBUG']         #extra compile flags for release

print '**** Compiling in ' + buildMode + ' mode...'

env = Environment()  # Initialize the environment


sourceTarget = 'UIToolkitCMDLineExample'
sourceFiles = Glob( "*.cpp" )

#make sure the sconscripts can get to the variables
Export('env', 'buildMode', 'debugcflags', 'releasecflags')

if buildMode == 'debug':
   env.Append(CCFLAGS=debugcflags)
else:
   env.Append(CCFLAGS=releasecflags)

env.Append(LIBPATH = ['/usr/lib', '/usr/local/lib'])
env.Program(sourceTarget, sourceFiles, LIBS=['chaos_uitoolkit', 'chaos_common', 'boost_program_options', 'boost_system','boost_thread', 'boost_chrono', 'boost_regex','boost_log','boost_log_setup','memcached','msgpack','msgpack-rpc','mpio'])